{% set name = "videoio" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff006088c9dc5bdd7ea73a7317177d0c3e67033114f68711a43d0b66bfc0e492

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - ffmpeg-python
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - videoio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vguzov/videoio
  summary: A small library for saving and loading RGB and uint16 (depth) frames as H.264 encoded video
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
